import { useCallback, useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import { toast } from "sonner";

export interface SharedGoal {
  id: string;
  name: string;
  target_amount: number;
  current_amount: number;
  preset_key: string;
  invite_code: string;
  created_by: string;
  is_completed: boolean;
  completed_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface SharedGoalSummary extends SharedGoal {
  member_count: number;
  my_role: "admin" | "member";
  pending_count: number; // for admins
}

export interface SharedGoalMember {
  id: string;
  shared_goal_id: string;
  user_id: string;
  role: "admin" | "member";
  total_contributed: number;
  joined_at: string;
  display_name?: string | null;
  avatar_url?: string | null;
}

export interface SharedJoinRequest {
  id: string;
  shared_goal_id: string;
  user_id: string;
  status: "pending" | "approved" | "rejected";
  created_at: string;
  display_name?: string | null;
}

export interface SharedContribution {
  id: string;
  shared_goal_id: string;
  user_id: string;
  amount: number;
  status: "pending" | "approved" | "rejected";
  created_at: string;
  decided_at: string | null;
  transaction_id: string | null;
  display_name?: string | null;
}

export function useSharedGoals() {
  const { user } = useAuth();
  const [goals, setGoals] = useState<SharedGoalSummary[]>([]);
  const [loading, setLoading] = useState(true);
  const [justCompleted, setJustCompleted] = useState<SharedGoal | null>(null);

  const fetchGoals = useCallback(async () => {
    if (!user) return;
    setLoading(true);
    // Get all memberships of the user
    const { data: memberships, error: mErr } = await supabase
      .from("shared_goal_members")
      .select("shared_goal_id, role")
      .eq("user_id", user.id);
    if (mErr) {
      console.error(mErr);
      setLoading(false);
      return;
    }
    if (!memberships || memberships.length === 0) {
      setGoals([]);
      setLoading(false);
      return;
    }
    const ids = memberships.map((m) => m.shared_goal_id);
    const roleMap = new Map(memberships.map((m) => [m.shared_goal_id, m.role as "admin" | "member"]));

    const [goalsRes, membersRes, joinRes, contribRes] = await Promise.all([
      supabase.from("shared_goals").select("*").in("id", ids),
      supabase.from("shared_goal_members").select("shared_goal_id").in("shared_goal_id", ids),
      supabase
        .from("shared_goal_join_requests")
        .select("shared_goal_id")
        .in("shared_goal_id", ids)
        .eq("status", "pending"),
      supabase
        .from("shared_goal_contributions")
        .select("shared_goal_id")
        .in("shared_goal_id", ids)
        .eq("status", "pending"),
    ]);
    if (goalsRes.error) {
      toast.error("Erro ao carregar vaquinhas");
      setLoading(false);
      return;
    }
    const memberCount = new Map<string, number>();
    membersRes.data?.forEach((m) => memberCount.set(m.shared_goal_id, (memberCount.get(m.shared_goal_id) ?? 0) + 1));
    const pendingCount = new Map<string, number>();
    joinRes.data?.forEach((j) => pendingCount.set(j.shared_goal_id, (pendingCount.get(j.shared_goal_id) ?? 0) + 1));
    contribRes.data?.forEach((c) => pendingCount.set(c.shared_goal_id, (pendingCount.get(c.shared_goal_id) ?? 0) + 1));

    const summaries: SharedGoalSummary[] = (goalsRes.data ?? []).map((g) => ({
      ...(g as SharedGoal),
      member_count: memberCount.get(g.id) ?? 0,
      my_role: roleMap.get(g.id) ?? "member",
      pending_count: roleMap.get(g.id) === "admin" ? pendingCount.get(g.id) ?? 0 : 0,
    }));
    summaries.sort((a, b) => +new Date(b.created_at) - +new Date(a.created_at));
    setGoals(summaries);
    setLoading(false);
  }, [user]);

  useEffect(() => {
    fetchGoals();
  }, [fetchGoals]);

  const createSharedGoal = useCallback(
    async (input: { name: string; target_amount: number; preset_key: string }) => {
      if (!user) return null;
      if (!input.name.trim() || input.target_amount <= 0) {
        toast.error("Preencha nome e valor objetivo válidos");
        return null;
      }
      // invite_code generated by trigger; pass placeholder that trigger will overwrite
      const { data, error } = await supabase
        .from("shared_goals")
        .insert({
          name: input.name.trim(),
          target_amount: input.target_amount,
          preset_key: input.preset_key,
          invite_code: "TEMPCODE",
          created_by: user.id,
        })
        .select("*")
        .single();
      if (error) {
        console.error(error);
        toast.error("Erro ao criar vaquinha");
        return null;
      }
      toast.success("Vaquinha criada!");
      await fetchGoals();
      return data as SharedGoal;
    },
    [user, fetchGoals],
  );

  const joinByCode = useCallback(
    async (code: string) => {
      if (!user) return null;
      const cleaned = code.trim().toUpperCase();
      if (cleaned.length < 4) {
        toast.error("Código inválido");
        return null;
      }
      const { data: lookup, error: lErr } = await supabase.rpc("find_shared_goal_by_code", { _code: cleaned });
      if (lErr || !lookup || lookup.length === 0) {
        toast.error("Vaquinha não encontrada");
        return null;
      }
      const goal = lookup[0];
      // already member?
      const { data: existing } = await supabase
        .from("shared_goal_members")
        .select("id")
        .eq("shared_goal_id", goal.id)
        .eq("user_id", user.id)
        .maybeSingle();
      if (existing) {
        toast.info("Você já é membro desta vaquinha");
        await fetchGoals();
        return goal;
      }
      const { error } = await supabase.from("shared_goal_join_requests").insert({
        shared_goal_id: goal.id,
        user_id: user.id,
      });
      if (error) {
        if (error.code === "23505") toast.info("Você já solicitou entrada");
        else toast.error("Erro ao solicitar entrada");
        return null;
      }
      toast.success("Solicitação enviada! Aguarde aprovação.");
      return goal;
    },
    [user, fetchGoals],
  );

  const approveJoinRequest = useCallback(
    async (req: SharedJoinRequest) => {
      if (!user) return;
      // Insert member
      const { error: mErr } = await supabase.from("shared_goal_members").insert({
        shared_goal_id: req.shared_goal_id,
        user_id: req.user_id,
        role: "member",
      });
      if (mErr && mErr.code !== "23505") {
        toast.error("Erro ao aprovar membro");
        return;
      }
      const { error } = await supabase
        .from("shared_goal_join_requests")
        .update({ status: "approved", decided_at: new Date().toISOString(), decided_by: user.id })
        .eq("id", req.id);
      if (error) {
        toast.error("Erro ao atualizar solicitação");
        return;
      }
      toast.success("Membro aprovado");
      await fetchGoals();
    },
    [user, fetchGoals],
  );

  const rejectJoinRequest = useCallback(
    async (req: SharedJoinRequest) => {
      if (!user) return;
      const { error } = await supabase
        .from("shared_goal_join_requests")
        .update({ status: "rejected", decided_at: new Date().toISOString(), decided_by: user.id })
        .eq("id", req.id);
      if (error) {
        toast.error("Erro ao rejeitar");
        return;
      }
      toast.success("Solicitação rejeitada");
      await fetchGoals();
    },
    [user, fetchGoals],
  );

  const requestContribution = useCallback(
    async (goal: SharedGoalSummary, amount: number) => {
      if (!user) return;
      if (amount <= 0) {
        toast.error("Valor inválido");
        return;
      }
      const { error } = await supabase.from("shared_goal_contributions").insert({
        shared_goal_id: goal.id,
        user_id: user.id,
        amount,
      });
      if (error) {
        toast.error("Erro ao enviar contribuição");
        return;
      }
      toast.success(
        goal.my_role === "admin" ? "Contribuição enviada — aprove na aba Solicitações" : "Aguardando aprovação do admin",
      );
      await fetchGoals();
    },
    [user, fetchGoals],
  );

  const approveContribution = useCallback(
    async (contrib: SharedContribution, goal: SharedGoal) => {
      if (!user) return;
      const { error } = await supabase.rpc("approve_shared_contribution", {
        _contribution_id: contrib.id,
      });
      if (error) {
        console.error(error);
        toast.error("Erro ao aprovar contribuição");
        return;
      }
      const newAmount = Number(goal.current_amount) + Number(contrib.amount);
      toast.success("Contribuição aprovada!");
      if (newAmount >= Number(goal.target_amount) && !goal.is_completed) {
        setJustCompleted({ ...goal, current_amount: newAmount, is_completed: true });
      }
      await fetchGoals();
    },
    [user, fetchGoals],
  );

  const rejectContribution = useCallback(
    async (contrib: SharedContribution) => {
      if (!user) return;
      const { error } = await supabase
        .from("shared_goal_contributions")
        .update({ status: "rejected", decided_at: new Date().toISOString(), decided_by: user.id })
        .eq("id", contrib.id);
      if (error) {
        toast.error("Erro ao rejeitar");
        return;
      }
      toast.success("Contribuição rejeitada");
      await fetchGoals();
    },
    [user, fetchGoals],
  );

  const withdrawFromShared = useCallback(
    async (goal: SharedGoal, amount: number) => {
      if (!user) return;
      if (amount <= 0) {
        toast.error("Valor inválido");
        return;
      }
      if (amount > Number(goal.current_amount)) {
        toast.error("Valor maior que o disponível");
        return;
      }
      const today = new Date().toISOString().split("T")[0];
      const { error: txErr } = await supabase.from("manual_transactions").insert({
        user_id: user.id,
        description: `Retirada vaquinha: ${goal.name}`,
        amount,
        type: "income",
        category: "Meta compartilhada",
        date: today,
        payment_method: "pix",
        shared_goal_id: goal.id,
      });
      if (txErr) {
        toast.error("Erro ao registrar retirada");
        return;
      }
      const newAmount = Math.max(0, Number(goal.current_amount) - amount);
      const { error } = await supabase
        .from("shared_goals")
        .update({ current_amount: newAmount })
        .eq("id", goal.id);
      if (error) {
        toast.error("Erro ao atualizar vaquinha");
        return;
      }
      toast.success("Valor retirado");
      await fetchGoals();
    },
    [user, fetchGoals],
  );

  const removeMember = useCallback(
    async (member: SharedGoalMember) => {
      if (!user) return;
      const { error } = await supabase.from("shared_goal_members").delete().eq("id", member.id);
      if (error) {
        toast.error("Erro ao remover membro");
        return;
      }
      toast.success("Membro removido");
      await fetchGoals();
    },
    [user, fetchGoals],
  );

  const promoteMember = useCallback(
    async (member: SharedGoalMember) => {
      if (!user) return;
      const { error } = await supabase
        .from("shared_goal_members")
        .update({ role: "admin" })
        .eq("id", member.id);
      if (error) {
        toast.error("Erro ao promover membro");
        return;
      }
      toast.success("Membro promovido a admin");
      await fetchGoals();
    },
    [user, fetchGoals],
  );

  const deleteSharedGoal = useCallback(
    async (goal: SharedGoal) => {
      if (!user) return;
      if (Number(goal.current_amount) > 0) {
        toast.error("Retire todo o saldo antes de excluir a vaquinha");
        return;
      }
      const { error } = await supabase.from("shared_goals").delete().eq("id", goal.id);
      if (error) {
        toast.error("Erro ao excluir vaquinha");
        return;
      }
      toast.success("Vaquinha excluída");
      await fetchGoals();
    },
    [user, fetchGoals],
  );

  const dismissCompleted = useCallback(() => setJustCompleted(null), []);

  return {
    goals,
    loading,
    refresh: fetchGoals,
    createSharedGoal,
    joinByCode,
    approveJoinRequest,
    rejectJoinRequest,
    requestContribution,
    approveContribution,
    rejectContribution,
    withdrawFromShared,
    removeMember,
    promoteMember,
    deleteSharedGoal,
    justCompleted,
    dismissCompleted,
  };
}

// Detail-view loaders
export async function loadSharedGoalDetail(goalId: string) {
  const [goalRes, membersRes, joinRes, contribRes] = await Promise.all([
    supabase.from("shared_goals").select("*").eq("id", goalId).maybeSingle(),
    supabase
      .from("shared_goal_members")
      .select("*")
      .eq("shared_goal_id", goalId)
      .order("total_contributed", { ascending: false }),
    supabase
      .from("shared_goal_join_requests")
      .select("*")
      .eq("shared_goal_id", goalId)
      .eq("status", "pending")
      .order("created_at", { ascending: false }),
    supabase
      .from("shared_goal_contributions")
      .select("*")
      .eq("shared_goal_id", goalId)
      .order("created_at", { ascending: false }),
  ]);
  // Fetch profiles for all referenced users
  const userIds = new Set<string>();
  membersRes.data?.forEach((m) => userIds.add(m.user_id));
  joinRes.data?.forEach((j) => userIds.add(j.user_id));
  contribRes.data?.forEach((c) => userIds.add(c.user_id));
  let profilesMap = new Map<string, { display_name: string | null; avatar_url: string | null }>();
  if (userIds.size > 0) {
    const { data: profiles } = await supabase.rpc("get_shared_goal_profiles", {
      _user_ids: Array.from(userIds),
    });
    profiles?.forEach((p: { id: string; display_name: string | null; avatar_url: string | null }) =>
      profilesMap.set(p.id, { display_name: p.display_name, avatar_url: p.avatar_url }),
    );
  }
  const enrich = <T extends { user_id: string }>(rows: T[] | null) =>
    (rows ?? []).map((r) => ({
      ...r,
      display_name: profilesMap.get(r.user_id)?.display_name ?? "Usuário",
      avatar_url: profilesMap.get(r.user_id)?.avatar_url ?? null,
    }));

  return {
    goal: goalRes.data as SharedGoal | null,
    members: enrich(membersRes.data as SharedGoalMember[] | null) as SharedGoalMember[],
    joinRequests: enrich(joinRes.data as SharedJoinRequest[] | null) as SharedJoinRequest[],
    contributions: enrich(contribRes.data as SharedContribution[] | null) as SharedContribution[],
  };
}
