// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lwgaktusfaawrzkeerkn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3Z2FrdHVzZmFhd3J6a2VlcmtuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUxNjUyOTYsImV4cCI6MjA5MDc0MTI5Nn0.WkQs0o6XwyMwH4Zz1E_IhnFnxyP4wEQrEk2HzfHFDbM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});